### ISSUE TITLE
safe-buffer missing from 2.0.9

### ISSUE THREAD

**Issue by RayBB** [Arlen22/TiddlyServer#25]
Hello,

When I download the latest release 2.0.9 and try to run it it says safe-buffer isn't installed.
```
ray@ray-VirtualBox:~/Documents/TiddlyServer$ node server.js 
module.js:538
    throw err;
    ^

Error: Cannot find module '../safe-buffer/safeBuffer.js'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at /home/ray/Documents/TiddlyServer/lib/websocket-server/WS/PerMessageDeflate.js:13:20
    at Object.<anonymous> (/home/ray/Documents/TiddlyServer/lib/websocket-server/WS/PerMessageDeflate.js:500:3)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)

```
I've tried running `npm install safe-buffer` but it didn't work.

However, if I go back 2.0.8 it works fine.

**Comment by BurningTreeC** [comment]
I had the same problem. it's because the file is named "safebuffer.js" <- lowercase

**Comment by RayBB** [comment]
Changing the file name did work!

Do you know if there's a reason this repo isn't using npm for the dependences?
I'm not too experienced with using it but it seems like it would be helpful.

**Comment by Arlen22** [comment]
Thank you. I've changed the file name.

**Comment by BurningTreeC** [comment]
thank you! and a big thanks for this server!
