### ISSUE TITLE
TiddlyServer on Synology Linux running Node 4.8

### ISSUE THREAD

**Issue by tiddler1234** [Arlen22/TiddlyServer#33]
I just found the problem in one of the closed issues: Seems like my NodeJS version is way to old as TiddlyServer requires at least version 6.

Hi Arlen,

TiddlyServer is great and makes working with Tiddlywikis so much easier but I faced a problem installing the Server on my Synology NAS running a custom Linux and only support a pretty old Node.JS version (so I understand if this is completly out of scope). Would be great if you could have a look anyway.

When trying to run TiddlyServer on my NAS the following happens:

> admin@REGE-NAS-P1:/volume1/web/TiddlyServer$ npm start
> 
> > tiddlyserver@2.0.12-master start /volume1/web/TiddlyServer
> > node server.js
> /volume1/web/TiddlyServer/src/server.js:202
>         return server_types_1.obs_stat(state)(favicon).mergeMap(([err, stat]) => {
>                                                                  ^SyntaxError: Unexpected token [
>     at exports.runInThisContext (vm.js:53:16)
>     at Module._compile (module.js:373:25)
>     at Object.Module._extensions..js (module.js:416:10)
>     at Module.load (module.js:343:32)
>     at Function.Module._load (module.js:300:12)
>     at Module.require (module.js:353:17)
>     at require (internal/module.js:12:17)
>     at Object.<anonymous> (/volume1/web/TiddlyServer/server.js:1:63)
>     at Module._compile (module.js:409:26)
>     at Object.Module._extensions..js (module.js:416:10)
> 
> npm ERR! Linux 3.10.102
> npm ERR! argv "/volume1/@appstore/Node.js_v4/usr/local/bin/node" "/usr/local/bin/npm" "start"
> npm ERR! node v4.8.4
> npm ERR! npm  v2.15.11
> npm ERR! code ELIFECYCLE
> npm ERR! tiddlyserver@2.0.12-master start: `node server.js`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the tiddlyserver@2.0.12-master start script 'node server.js'.
> npm ERR! This is most likely a problem with the tiddlyserver package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node server.js
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs tiddlyserver
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!
> npm ERR!     npm owner ls tiddlyserver
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /volume1/web/TiddlyServer/npm-debug.log

[npm-debug.log](https://github.com/Arlen22/TiddlyServer/files/1619613/npm-debug.log)

**Comment by tiddler1234** [comment]
Found that the Node.JS version is way to old on the Synology, need to figure out how to install a newer release.
