### ISSUE TITLE
Cannot start the server, because of SyntaxErrors

### ISSUE THREAD

**Issue by KithorasCarzyl** [Arlen22/TiddlyServer#34]
I tried to install the server on my pc, but it couldn't start because of the following error.

```
C:\Users\xxx\Downloads\TiddlyServer-2.0.11\src\server.js:3
const rx_1 = require("../lib/rx");
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\xxx\Downloads\TiddlyServer-2.0.11\server.js:1:63)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

If I remove "use strict" from the file, it will show the following error:

```
C:\Users\xxx\Downloads\TiddlyServer-2.0.11\src\server.js:12
process.on('uncaughtException', err => {
                                    ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\xxx\Downloads\TiddlyServer-2.0.11\server.js:1:63)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

---
Node Version: v8.9.4
Windows 10 Pro

**Comment by KithorasCarzyl** [comment]
Hmm, you're right: If I open up my usual cmd and type in `node -v` it will show `v0.12.2` to me.
If I open up my node command prompt and type in the same it will show `v8.9.4`.

Weird, but now it works; thanks.
