### ISSUE TITLE
Data folders crashing on Termux

### ISSUE THREAD

**Issue by Marxsal** [Arlen22/TiddlyServer#52]
I get the following error when attempting to open data folders with TS on termux. Single files seem (so far) to save OK.

Is there something I need to do/tweak to make this work?

Thank you!
-- Mark

{ Error: Cannot find module '../../TiddlyWiki5-Jermolene/boot/boot.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:649:15)
    at Function.Module._load (internal/modules/cjs/loader.js:575:25)
    at Module.require (internal/modules/cjs/loader.js:705:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at loadDataFolderTiddlyWiki (/storage/emulated/0/Download/TiddlyServer-2.0.14/src/datafolder.js:142:17)
    at a.server_types_1.obs_readFile.subscribe [as _next] (/storage/emulated/0/Download/TiddlyServer-2.0.14/src/datafolder.js:132:13)
    at a.__tryOrUnsub (/storage/emulated/0/Download/TiddlyServer-2.0.14/lib/Rx.min.js:43:377)
    at a.next (/storage/emulated/0/Download/TiddlyServer-2.0.14/lib/Rx.min.js:42:227)
    at a._next (/storage/emulated/0/Download/TiddlyServer-2.0.14/lib/Rx.min.js:40:393)
    at a.next (/storage/emulated/0/Download/TiddlyServer-2.0.14/lib/Rx.min.js:40:64)
    at cb (/storage/emulated/0/Download/TiddlyServer-2.0.14/src/server-types.js:617:14)
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:54:3) code: 'MODULE_NOT_FOUND' }
caught process uncaughtException
closing server

**Comment by Arlen22** [comment]
The error indicates that it can't find the TiddlyWiki folder. Apparently I had it set to the wrong one on my machine. The temporary fix is to move the tiddlywiki folder out of the TiddlyServer folder and  name it `TiddlyWiki5-Jermolene`. So it would be next to the TiddlyServer folder. I'm sorry for this, and I will try to fix it shortly.

**Comment by Marxsal** [comment]
Perhaps I'm not understanding your fix properly. Now it won't even start.

I moved tiddlywiki folder one directory up so that it is next to TiddlyServer-2.0.14. I renamed tiddlywiki to TiddlyWiki5-Jermolene.

From inside TiddlyServer-2.0.14 I launched: node server.js 

I get a really long error instantly. It looks like it can't find boot.js.

**Comment by Arlen22** [comment]
What is the long error you get?

**Comment by Arlen22** [comment]
I'm sorry for the inconvenience. Please use [2.0.14-fixed](https://github.com/Arlen22/TiddlyServer/releases/tag/2.0.14-fixed) instead of 2.0.14. You can delete the `TiddlyWiki5-Jermolene` folder. The process for upgrading is to extract the TiddlyServer folder and copy your settings.json file over from the old folder.

**Comment by Marxsal** [comment]
Thanks, @Arlen22 -- the fix seems to work!
