### ISSUE TITLE
[v2.1.0-beta] Upgrade-settings exits with error

### ISSUE THREAD

**Issue by mauloop** [Arlen22/TiddlyServer#53]
Dear Arlen22,

I'm interested in running TW5.1.19 on TiddlyServer, so I downloaded v2.1.0-beta.
I ran this command to convert old settings file:

`node upgrade-setting settings_2-0-14.json settings_2-1-0.json`

and it returned the following error:

```
The conversion failed because:

K:\MK\opt64\TiddlyServer-2.1.0-beta\upgrade-settings.js:39
newSettings = NewDefaultSettings(newSettings);
              ^

TypeError: NewDefaultSettings is not a function
    at Object.<anonymous> (K:\MK\opt64\TiddlyServer-2.1.0-beta\upgrade-settings.js:39:15)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

```
My environment is Win 10 64 bit + Node.js 10.15.3

Thanks in advance for your help.

**Comment by Arlen22** [comment]
I apologize for this. Please use this version: https://github.com/Arlen22/TiddlyServer/blob/7df407e94519a5ce92c44ee745f1728fd582ec1e/upgrade-settings.js

Another thing you can do is create a new settings.json file as in the readme and copy the tree property over from the upgraded file.

**Comment by mauloop** [comment]
It worked! Thanks Arlen22. There are lots of differences in the syntax. I'm in doubt I would have been able to recreate it by hands simply looking at the example.

I commented out most of the paths in the converted file. Since 2.1 is still in beta stage I want proceed with caution, but I really can't wait to test it.
