### ISSUE TITLE
[v2.1.1.-beta] Errors when running 

### ISSUE THREAD

**Issue by Marxsal** [Arlen22/TiddlyServer#56]
Windows 7.
I copied over my old working settings file as settings-old, and upgraded it. Running the server immediately generated a plethora of errors (below).

Thanks!
Mark

---

Successfully converted settings. The new file is
C:\Apps\TiddlyServer-2.1.1-beta\settings.json

C:\Apps\TiddlyServer-2.1.1-beta>node server.js
Settings file: C:\Apps\TiddlyServer-2.1.1-beta\settings.json
TypeError: p is not a function
    at process.de (C:\Apps\TiddlyServer-2.1.1-beta\lib\bundled-lib.js:161:524800
)
    at emitTwo (events.js:106:13)
    at process.emit (events.js:191:7)
    at process.emit (C:\Apps\TiddlyServer-2.1.1-beta\lib\source-map-support-lib.
js:1771:21)
    at emitPendingUnhandledRejections (internal/process/promises.js:56:22)
    at runMicrotasksCallback (internal/process/next_tick.js:61:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
caught process uncaughtException
C:\Apps\TiddlyServer-2.1.1-beta\lib\bundled-lib.js:161
!function(e){"use strict";function A(){for(var e=arguments.length,A=Array(e),t=0
;t<e;t++)A[t]=arguments[t];if(A.length>1){A[0]=A[0].slice(0,-1);for(var r=A.leng
th-1,i=1;i<r;++i)A[i]=A[i].slice(1,-1);return A[r]=A[r].slice(1),A.join("")}retu
rn A[0]}function t(e){return"(?:"+e+")"}function r(e){return void 0===e?"undefin
ed":null===e?"null":Object.prototype.toString.call(e).split(" ").pop().split("]"
).shift().toLowerCase()}function i(e){return e.toUpperCase()}function a(e){var r
=A("[0-9]","[A-Fa-f]"),i=t(t("%[EFef]"+r+"%"+r+r+"%"+r+r)+"|"+t("%[89A-Fa-f]"+r+
"%"+r+r)+"|"+t("%"+r+r)),a="[\\!\\$\\&\\'\\(\\)\\*\\+\\,\\;\\=]",n=A("[\\:\\/\\?
\\#\\[\\]\\@]",a),o=e?"[\\xA0-\\u200D\\u2010-\\u2029\\u202F-\\uD7FF\\uF900-\\uFD
CF\\uFDF0-\\uFFEF]":"[]",s=e?"[\\uE000-\\uF8FF]":"[]",c=A("[A-Za-z]","[0-9]","[\
\-\\.\\_\\~]",o),u=t("[A-Za-z]"+A("[A-Za-z]","[0-9]","[\\+\\-\\.]")+"*"),g=t(t(i
+"|"+A(c,a,"[\\:]"))+"*"),h=(t(t("25[0-5]")+"|"+t("2[0-4][0-9]")+"|"+t("1[0-9][0
-9]")+"

TypeError: p is not a function
    at process.de (C:\Apps\TiddlyServer-2.1.1-beta\lib\bundled-lib.js:161:524800
)
    at emitTwo (events.js:106:13)
    at process.emit (events.js:191:7)
    at process.emit (C:\Apps\TiddlyServer-2.1.1-beta\lib\source-map-support-lib.
js:1771:21)
    at emitPendingUnhandledRejections (internal/process/promises.js:56:22)
    at runMicrotasksCallback (internal/process/next_tick.js:61:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

**Comment by Marxsal** [comment]
I just noticed there is some new FAQ below. Sorry.
