### ISSUE TITLE
Upgrading 2.0.14 to  2.1

### ISSUE THREAD

**Issue by AnthonyMuscio** [Arlen22/TiddlyServer#65]
I had to rename my existing settings.json to oldsettings.json to run the command
`node upgrade-settings.js oldsettings.json setting.json`
then I got with start.cmd
```
C:\Data\TW5\Hosting\TiddlyServer.2.1>start.cmd
C:\Data\TW5\Hosting\TiddlyServer.2.1>node server
Settings file: C:\Data\TW5\Hosting\TiddlyServer.2.1\settings.json
uncaught error during server startup
{ Error: Cannot find module 'C:\Data\TW5\Hosting\TiddlyServer.2.1\settings.schema.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.loadSettings (C:\Data\TW5\Hosting\TiddlyServer.2.1\src\server-types.ts:137:39)
    at server.libsReady.then (C:\Data\TW5\Hosting\TiddlyServer.2.1\server.js:19:45) code: 'MODULE_NOT_FOUND' }
exiting
(node:9716) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
C:\Data\TW5\Hosting\TiddlyServer.2.1>pause
```

So I manually renamed settings-2-1.schema.json to settings.schema.json but not the others with similar names

Now I get
```
C:\Data\TW5\Hosting\TiddlyServer.2.1>node server
Settings file: C:\Data\TW5\Hosting\TiddlyServer.2.1\settings.json
ADDITIONALPROPERTIES: settings.bindInfo.localAddressPermissions['localhost'] should NOT have additional properties
ADDITIONALPROPERTIES: settings.bindInfo.localAddressPermissions['localhost'] should NOT have additional properties
REQUIRED: settings.bindInfo.localAddressPermissions['localhost'] should have required property 'writeErrors'
REQUIRED: settings.bindInfo.localAddressPermissions['localhost'] should have required property 'websockets'
REQUIRED: settings.bindInfo.localAddressPermissions['localhost'] should have required property 'registerNotice'
ADDITIONALPROPERTIES: settings.bindInfo.localAddressPermissions['*'] should NOT have additional properties
ADDITIONALPROPERTIES: settings.bindInfo.localAddressPermissions['*'] should NOT have additional properties
REQUIRED: settings.bindInfo.localAddressPermissions['*'] should have required property 'writeErrors'
REQUIRED: settings.bindInfo.localAddressPermissions['*'] should have required property 'websockets'
REQUIRED: settings.bindInfo.localAddressPermissions['*'] should have required property 'registerNotice'
TYPE: settings.bindInfo.https should be string
32 32 64 16
Creating servers as http
 SERVER  2019-08-04 11:55:49 server 192.168.1.81 listening
Open your browser and type in one of the following:
http://192.168.1.81:80
```

It seems to be work though.

Regqards
Tony

**Comment by Arlen22** [comment]
The last log you posted is normal. The error messages are the schema checker checking the settings, but I don't have this finished yet. Thank you for mentioning the schema property in the upgraded settings. I'll take a look at that.
