### ISSUE TITLE
Updated Tiddlywiki does not start because of TypeErrors

### ISSUE THREAD

**Issue by NoxMortem** [Arlen22/TiddlyServer#67]
TiddlyServer 2.1.1-beta, 2.0.14-fixed
NodeJs v12.9.0
Windows 10 x64
# TiddlyWiki  5.1.20
```
twboot-C:\Users\Kevin\Dropbox\Tools\tiddlyserver\tiddlywiki\wiki\story\testrunde: 373.916ms
 DAT 2019-08-25 11:12:26 error starting /Testrunde at C:\Users\Kevin\Dropbox\Tools\tiddlyserver\tiddlywiki\wiki\story\testrunde: TypeError: self.addIndexer is not a function
                             at $:/core/modules/wiki.js:37:8
                             at Object.$tw.utils.each (C:\Users\Kevin\Dropbox\Tools\tiddlyserver\tiddlywiki\boot\boot.js:83:12)
                             at $tw.Wiki.exports.addIndexersToWiki ($:/core/modules/wiki.js:36:12)
                             at Object.exports.startup ($:/core/modules/startup/load-modules.js:31:11)
                             at Object.$tw.boot.executeNextStartupTask (C:\Users\Kevin\Dropbox\Tools\tiddlyserver\tiddlywiki\boot\boot.js:2120:10)
                             at Object.$tw.boot.startup (C:\Users\Kevin\Dropbox\Tools\tiddlyserver\tiddlywiki\boot\boot.js:2077:11)
                             at C:\Users\Kevin\Dropbox\Tools\tiddlyserver\tiddlywiki\boot\boot.js:2230:12
                             at Object.$tw.boot.decryptEncryptedTiddlers (C:\Users\Kevin\Dropbox\Tools\tiddlyserver\tiddlywiki\boot\boot.js:1500:2)
                             at Object.$tw.boot.boot [as boot] (C:\Users\Kevin\Dropbox\Tools\tiddlyserver\tiddlywiki\boot\boot.js:2228:11)
                             at loadDataFolderTiddlyWiki (C:\Users\Kevin\Dropbox\Tools\tiddlyserver\src\datafolder.ts:195:12)
TypeError: undefined is not a function
    at C:\Users\Kevin\Dropbox\Tools\tiddlyserver\src\datafolder.ts:260:19
    at Array.forEach (<anonymous>)
    at doError (C:\Users\Kevin\Dropbox\Tools\tiddlyserver\src\datafolder.ts:260:11)
    at complete (C:\Users\Kevin\Dropbox\Tools\tiddlyserver\src\datafolder.ts:205:11)
    at loadDataFolderTiddlyWiki (C:\Users\Kevin\Dropbox\Tools\tiddlyserver\src\datafolder.ts:199:3)
    at a._next (C:\Users\Kevin\Dropbox\Tools\tiddlyserver\src\datafolder.ts:164:4)
    at a.__tryOrUnsub (C:\Users\Kevin\Dropbox\Tools\tiddlyserver\lib\Rx.min.js:43:377)
    at a.next (C:\Users\Kevin\Dropbox\Tools\tiddlyserver\lib\Rx.min.js:42:227)
    at a._next (C:\Users\Kevin\Dropbox\Tools\tiddlyserver\lib\Rx.min.js:40:393)
    at a.next (C:\Users\Kevin\Dropbox\Tools\tiddlyserver\lib\Rx.min.js:40:64)
    at cb (C:\Users\Kevin\Dropbox\Tools\tiddlyserver\src\server-types.ts:820:10)
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)
caught process uncaughtException
```
# TiddlyWiki 5.1.19, 5.1.18
```
twboot-C:\Users\Kevin\Dropbox\Tools\tiddlyserver\tiddlywiki\wiki\story\testrunde: 1292.549ms
 DAT 2019-08-25 11:33:10 error starting /Testrunde at C:\Users\Kevin\Dropbox\Tools\tiddlyserver\tiddlywiki\wiki\story\testrunde: TypeError: Cannot read property 'set' of undefined
                             at complete (C:\Users\Kevin\Dropbox\Tools\tiddlyserver\src\datafolder.js:175:16)
                             at C:\Users\Kevin\Dropbox\Tools\tiddlyserver\src\datafolder.js:152:13
                             at Object.$tw.boot.executeNextStartupTask (C:\Users\Kevin\Dropbox\Tools\tiddlyserver\tiddlywiki\boot\boot.js:2123:3)
                             at asyncTaskCallback (C:\Users\Kevin\Dropbox\Tools\tiddlyserver\tiddlywiki\boot\boot.js:2089:20)
                             at Commander.$tw.Commander.output [as callback] ($:/core/modules/startup/commands.js:29:4)
                             at Commander.executeNextCommand ($:/core/modules/commander.js:74:8)
                             at Commander.execute ($:/core/modules/commander.js:64:7)
                             at Object.exports.startup ($:/core/modules/startup/commands.js:34:12)
                             at Object.$tw.boot.executeNextStartupTask (C:\Users\Kevin\Dropbox\Tools\tiddlyserver\tiddlywiki\boot\boot.js:2116:10)
                             at Object.$tw.boot.executeNextStartupTask (C:\Users\Kevin\Dropbox\Tools\tiddlyserver\tiddlywiki\boot\boot.js:2114:21)
                             at Object.$tw.boot.executeNextStartupTask (C:\Users\Kevin\Dropbox\Tools\tiddlyserver\tiddlywiki\boot\boot.js:2114:21)
                             at Object.$tw.boot.executeNextStartupTask (C:\Users\Kevin\Dropbox\Tools\tiddlyserver\tiddlywiki\boot\boot.js:2114:21)
                             at Object.$tw.boot.executeNextStartupTask (C:\Users\Kevin\Dropbox\Tools\tiddlyserver\tiddlywiki\boot\boot.js:2114:21)
                             at Object.$tw.boot.startup (C:\Users\Kevin\Dropbox\Tools\tiddlyserver\tiddlywiki\boot\boot.js:2067:11)
                             at C:\Users\Kevin\Dropbox\Tools\tiddlyserver\tiddlywiki\boot\boot.js:2220:12
                             at Object.$tw.boot.decryptEncryptedTiddlers (C:\Users\Kevin\Dropbox\Tools\tiddlyserver\tiddlywiki\boot\boot.js:1490:2)
                             at Object.$tw.boot.boot [as boot] (C:\Users\Kevin\Dropbox\Tools\tiddlyserver\tiddlywiki\boot\boot.js:2218:11)
                             at loadDataFolderTiddlyWiki (C:\Users\Kevin\Dropbox\Tools\tiddlyserver\src\datafolder.js:151:18)
                             at a._next (C:\Users\Kevin\Dropbox\Tools\tiddlyserver\src\datafolder.js:132:13)
                             at a.__tryOrUnsub (C:\Users\Kevin\Dropbox\Tools\tiddlyserver\lib\Rx.min.js:43:377)
                             at a.next (C:\Users\Kevin\Dropbox\Tools\tiddlyserver\lib\Rx.min.js:42:227)
                             at a._next (C:\Users\Kevin\Dropbox\Tools\tiddlyserver\lib\Rx.min.js:40:393)
                             at a.next (C:\Users\Kevin\Dropbox\Tools\tiddlyserver\lib\Rx.min.js:40:64)
                             at cb (C:\Users\Kevin\Dropbox\Tools\tiddlyserver\src\server-types.js:617:14)
                             at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)
TypeError: undefined is not a function
    at C:\Users\Kevin\Dropbox\Tools\tiddlyserver\src\datafolder.js:214:22
    at Array.forEach (<anonymous>)
    at doError (C:\Users\Kevin\Dropbox\Tools\tiddlyserver\src\datafolder.js:214:14)
    at complete (C:\Users\Kevin\Dropbox\Tools\tiddlyserver\src\datafolder.js:161:20)
    at loadDataFolderTiddlyWiki (C:\Users\Kevin\Dropbox\Tools\tiddlyserver\src\datafolder.js:156:9)
    at a._next (C:\Users\Kevin\Dropbox\Tools\tiddlyserver\src\datafolder.js:132:13)
    at a.__tryOrUnsub (C:\Users\Kevin\Dropbox\Tools\tiddlyserver\lib\Rx.min.js:43:377)
    at a.next (C:\Users\Kevin\Dropbox\Tools\tiddlyserver\lib\Rx.min.js:42:227)
    at a._next (C:\Users\Kevin\Dropbox\Tools\tiddlyserver\lib\Rx.min.js:40:393)
    at a.next (C:\Users\Kevin\Dropbox\Tools\tiddlyserver\lib\Rx.min.js:40:64)
    at cb (C:\Users\Kevin\Dropbox\Tools\tiddlyserver\src\server-types.js:617:14)
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)
caught process uncaughtException
closing server
(node:23164) Warning: No such label 'twboot-C:\Users\Kevin\Dropbox\Tools\tiddlyserver\tiddlywiki\wiki\story\testrunde' for console.timeEnd()
finished processing for some reason
 syncer-server-filesystem: Dispatching 'save' task: $:/StoryList
 filesystem: Saved file C:\Users\Kevin\Dropbox\Tools\tiddlyserver\tiddlywiki\wiki\story\testrunde\tiddlers\$__StoryList.tid
```

**Comment by NoxMortem** [comment]
The only way I was able to get tiddlywiki 5.1.19 to run (I required 5.1.18 to get global hotkeys)

- Delete everything
- Copy TiddlyServer-2.1.0-beta to target
- Copy and overwrite TiddlyServer-2.1.1-beta to target (it might be unecessary to first use 2.1.0, but I have no time to try it out)
- Rename settings-2.1.schema.json to settings.schema.json (or change the schema in the example-settings.json)
- Copy example-settings.json and change it to the following example
```
{
  "tree": {
    "$element": "folder",
    "path": ".\\tiddlywiki\\wiki\\story\\testrunde",
  },
  "bindInfo": {
		"bindWildcard": true
  },
  "putsaver": {
    "backupDirectory": "../backups"
  },
  "$schema": "./settings.schema.json"
}
```

**Comment by Arlen22** [comment]
Please try downloading the current master from this link https://github.com/Arlen22/TiddlyServer/archive/18d0e718b0e606bbc318dfd4156f90b90506c1cf.zip and use this settings.json file. When you unzip the file, make sure it is being unzipped to an empty folder so there is no chance of mixing files (even though this should not usually matter).


```jsonc
{
  "tree": "../tiddlyserver/tiddlywiki/wiki/story/testrunde", //this is the data folder from the other installation
  "bindInfo": {
    "bindWildcard": true
  },
  "putsaver": {
    "backupDirectory": "../backups"
  },
  "$schema": "./settings-2-1.schema.json"
}
```

**Comment by Arlen22** [comment]
Recently I had been making a lot of changes, so you may have downloaded a broken version of master. Or perhaps there was a bug in the link I had posted to the tiddlywiki group. In either case, use the link I posted above to download master and this one should be working properly. I've been using it some over the weekend and haven't noticed any problems so far. Here is the link again for your convenience. https://github.com/Arlen22/TiddlyServer/archive/18d0e718b0e606bbc318dfd4156f90b90506c1cf.zip
