### ISSUE TITLE
Request: Update documentation with more examples on how to mount multiple tiddlywikis with 2.1

### ISSUE THREAD

**Issue by NoxMortem** [Arlen22/TiddlyServer#70]
Could someone provide some examples for the new tree syntax on how to mount 2 tiddlywikis? Before that it was super easy with
```
{
  "tree": {
       "Testrunde": ".\\tiddlywiki\\wiki\\story\\testrunde",
       "Testrunde2": ".\\tiddlywiki\\wiki\\story\\testrunde2"
  },
  "bindInfo": {
		"bindWildcard": true
  },
  "putsaver": {
    "backupDirectory": "../backups"
  },
  "$schema": "./settings.schema.json"
}
```
This syntax is not supported in 2.1 anymore it fails loading with
```
{
  Testrunde: '.\\tiddlywiki\\wiki\\story\\testrunde',
  Template: '.\\tiddlywiki\\wiki\\template\\testrunde'
}
 APP 2019-08-25 12:03:33 Uncaught error in the request handler: property item must be a TreePath
 APP 2019-08-25 12:03:33 Uncaught error in the request handler: Cannot read property 'find' of undefined
 APP 2019-08-25 12:03:33 TypeError: Cannot read property 'find' of undefined
                             at treeWalker (C:\Users\Kevin\Dropbox\Tools\tiddlyserver\src\server-types.ts:724:26)
                             at Object.resolvePath (C:\Users\Kevin\Dropbox\Tools\tiddlyserver\src\server-types.ts:771:15)
                             at a.project (C:\Users\Kevin\Dropbox\Tools\tiddlyserver\src\tiddlyserver.ts:77:16)
                             at a._tryNext (C:\Users\Kevin\Dropbox\Tools\tiddlyserver\lib\Rx.min.js:139:209)
                             at a._next (C:\Users\Kevin\Dropbox\Tools\tiddlyserver\lib\Rx.min.js:139:111)
                             at a.next (C:\Users\Kevin\Dropbox\Tools\tiddlyserver\lib\Rx.min.js:40:64)
                             at a._subscribe (C:\Users\Kevin\Dropbox\Tools\tiddlyserver\lib\Rx.min.js:57:497)
                             at a.b._trySubscribe (C:\Users\Kevin\Dropbox\Tools\tiddlyserver\lib\Rx.min.js:45:371)
                             at a.b.subscribe (C:\Users\Kevin\Dropbox\Tools\tiddlyserver\lib\Rx.min.js:45:197)
                             at b.call (C:\Users\Kevin\Dropbox\Tools\tiddlyserver\lib\Rx.min.js:138:254)
                             at b.subscribe (C:\Users\Kevin\Dropbox\Tools\tiddlyserver\lib\Rx.min.js:45:135)
                             at b.call (C:\Users\Kevin\Dropbox\Tools\tiddlyserver\lib\Rx.min.js:106:24)
                             at b.subscribe (C:\Users\Kevin\Dropbox\Tools\tiddlyserver\lib\Rx.min.js:45:135)
                             at Object.handleTiddlyServerRoute (C:\Users\Kevin\Dropbox\Tools\tiddlyserver\src\tiddlyserver.ts:126:5)
                             at C:\Users\Kevin\Dropbox\Tools\tiddlyserver\src\server.ts:390:9
                             at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

**Comment by NoxMortem** [comment]
Working solution:
```
{
  "tree": {
	"$element" : "group",
	"indexPath" : "group1",
	"$children" :
	{
	  "Testrunde1": {
	    "$element":"folder",
        "path": ".\\tiddlywiki\\wiki\\story\\testrunde"
	  },
	  "Testrunde2": {
	    "$element":"folder",
        "path": ".\\tiddlywiki\\wiki\\template\\testrunde"
	  }
	}
  },
  "bindInfo": {
		"bindWildcard": true
  },
  "putsaver": {
    "backupDirectory": "../backups"
  },
  "$schema": "./settings.schema.json"
}
```

However, the documentation should be updated to reflect this. I am able to figure this out, but others should not have to understand the Settings documentation which is correct but technical.

**Comment by Arlen22** [comment]
Your first example was supposed to work as well so this is a bug. I will
fix this as soon as I can.

**Comment by Arlen22** [comment]
I just tested it and it is fixed in the revision I posted at https://github.com/Arlen22/TiddlyServer/issues/67. Feel free to reopen this or open a new issue if you still experience problems.
